old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        group_event:
            connection:       default
            exchange_options: { name: 'old_sound_rabbit_mq.group_event', type: direct }
        account_event:
            connection:       default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }

    consumers:
        group_event:
            connection:       default
            exchange_options: { name: 'old_sound_rabbit_mq.group_event', type: direct }
            queue_options:    { name: 'old_sound_rabbit_mq.consumer.group_event'}
            callback:         App\Consumer\GroupEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        account_event_0:
            connection:       default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.account_event_0', routing_key: '20' }
            callback: App\Consumer\AccountEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        account_event_1:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.account_event_1', routing_key: '20' }
            callback:               App\Consumer\AccountEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        account_event_2:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.account_event_2', routing_key: '20' }
            callback:               App\Consumer\AccountEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        account_event_3:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.account_event_3', routing_key: '20' }
            callback:               App\Consumer\AccountEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        account_event_4:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.account_event_4', routing_key: '20' }
            callback:               App\Consumer\AccountEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        account_event_5:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.account_event_5', routing_key: '20' }
            callback:               App\Consumer\AccountEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        account_event_6:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.account_event_6', routing_key: '20' }
            callback:               App\Consumer\AccountEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        account_event_7:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.account_event_7', routing_key: '20' }
            callback:               App\Consumer\AccountEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        account_event_8:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.account_event_8', routing_key: '20' }
            callback:               App\Consumer\AccountEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        account_event_9:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.account_event', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.account_event_9', routing_key: '20' }
            callback:               App\Consumer\AccountEvent\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
